// <auto-generated />
namespace TutoringMarket.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tutor_Subject_Relationadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tutor_Subject_Relationadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201705301308325_Tutor_Subject_Relation added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
