// <auto-generated />
namespace TutoringMarket.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TutorIdadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TutorIdadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201705161217567_Tutor-Id added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
